---
title: "Scientific Events"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{css}
d-title {
    display: none;
  }
```

<style>
body {
text-align: justify;
color: #36454F}
</style>

## Conference talks


# 2025 (to come)

-  Bristish Ecological Society (BES): <span style="color: #00cc99;">*Are protected areas safeguarding taxonomic, functional and phylogenetic rarity under future change in Mediterranean forests?* </span>


# 2024

- Bristish Ecological Society (BES): <span style="color: #00cc99;">*Apprehending Past and Present Drivers of Functional and Phylogenetic Diversity in Euro-Mediterranean Forests* </span>


# 2022

- International Symposium on Coral Reefs (ICRS): <span style="color: #00cc99;">*A new framework based on synchronised cameras to measure fish abundance* </span>


# 2021

- International Symposium on Coral Reefs (ICRS): <span style="color: #00cc99;">*Tropical exotic fish are key herbivores in the Mediterranean sea* </span>

- R Rencontres 2021: <span style="color: #00cc99;">*Presentation of the mFD package*</span> - Recording of the talk [here](https://www.youtube.com/watch?v=fvnTqqnEEB0)



## Conference posters

# 2026 (to come)

- International Biogeography Symposium (IBS): <span style="color: #00cc99;">*Do Protected Areas effectively preserve rarity across taxa and diversity facets under future change?* </span>


# 2023

- International Biogeography Symposium (IBS): <span style="color: #00cc99;">*Exploring diversity dimensions to protect Euro-Mediterranean forests* </span>

[**See my poster here**](pdfs/IBS_Poster_CMagneville_versfinale.pdf) 


## Co-organised workshops


# 2022

- I had the opportunity to co-organise a [**Workshop on Functional Rarity and Diversity in Ecology**](https://frbcesab.github.io/workshop-free/) led by the [FRB-CESAB](https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/) and the [FREE Research Group](https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/free/). During this workshop, we did a practical on the use of the [mFD](https://onlinelibrary.wiley.com/doi/10.1111/ecog.05904) and the [funrar](https://onlinelibrary.wiley.com/doi/10.1111/ddi.12629) R packages.
Co-organisation with: [Matthias Grenié](https://rekyt.github.io/) and [Sébastien Villéger](https://umr-marbec.fr/membre/sebastien-villeger/?highlight=villeger)


## Scientific popularization


# 2023

- I conducted a **workshop** (Co-facilitated with Valentine Fleuré) aimed at **primary school classes** on the use of artificial intelligence to explore ecosystem functioning for World Oceans Day aimed  (UMR MARBEC - Sete)

# 2022

- I participated to the "Ma Thèse en 180 secondes" **(Three Minutes Thesis)** competition: the goal is to resume the thesis subject in 3 minutes for a non-scientific audience. My colleagues and I had the opportunity to speak in front of about 450 persons, it was an incredible experience! My talk in *french* [here](https://www.youtube.com/watch?v=vf_43KJPgkE).


