---
title: "Teachings"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{css}
d-title {
    visibility: hidden;
  }
```

<style>
body {
text-align: justify;
color: #36454F}
</style>

Teaching is a part of my job that I absolutely love. 
Transmitting knowledge, finding new ways to explain key concepts, 
and engaging with students also helps me evolve in my research work.

<span style="color: #93A588;">2019 - 2022</span>

Lectures, tutorial groups and practical works (french) for Bachelor and Master 
at the [University of Montpellier](https://www.umontpellier.fr/en/) in:

- Biology of Organisms
- Functional Ecology
- Description of data variability
- Biostatistics and R coding


<span style="color: #93A588;">2023 - 2025</span>

At [Aarhus University](https://international.au.dk/) (english):
- Guide a Bachelor research project: creation of a research project based on existing data, to make students think and realize the different steps of a research project - literature search, development of hypotheses, data analyses in R, introduction to functional diversity analyses, report redaction.
- (more coming soon)



